const blogs = [
    {
        id: 1,
        title: "Mastering JavaScript for Beginners",
        content: "JavaScript is a programing language used in web development...",
        categories: ["Programming", "JavaScript", "Web Development"],
        tags: ["JavaScript", "Coding Basics", "Frontend"],
        popularity: 8.5,
        isPopular: false,
        isRecent: true,
        date: "2023-80-01",
        image: "/images/js.png",
        comments: ["Very helpful article!", "Great tips, thanks!"],
    },
        {
        id: 2,
        title: "The Future of AI in Healthcare",
        content: "Artificial Intelligence is revolutionizing the healthcare industry...",
        categories: ["AI", "Healthcare", "Technology"],
        tags: ["AI", "Healthcare", "Innovation"],
        popularity: 8.5,
        isPopular: true,
        isRecent: true,
        date: "2024-09-25",
        image: "/images/ai.png",
        comments: ["This is amazing!", "AI is the future!"],
    },
    {
        id: 3,
        title: "UI/UX Trends to Watch in 2024",
        content: "The design world is constantly evolving. Here's what to expect...",
        categories: ["UI/UX", "Design"],
        tags: ["UI", "UX", "Trends"],
        popularity: 8.8,
        isPopular: false,
        isRecent: true,
        date: "2024-10-10",
        image: "/images/ui-ux.avif",
        comments: ["Love!", "futuristic."],
    },
    {
        id: 4,
        title: "The Rise of Web3 and Blockchain",
        content: "Blockchain technology is at the forefront of Web3 innovations...",
        categories: ["Web3", "Blockchain", "Cryptocurrency"],
        tags: ["Blockchain", "Web3", "Crypto"],
        popularity: 8.9,
        isPopular: false,
        isRecent: true,
        date: "2024-04-12",
        image: "/images/blockchain.avif",
        comments: ["Very exciting topic!", "Crypto is the future!"],
    },
    {
        id: 5,
        title: "Introduction to Machine Learning with Python",
        content: "Machine learning with Python is a powerful combination that allows you to solve complex problems with ease...",
        categories: ["Machine Learning", "Python", "AI"],
        tags: ["Machine Learning", "Python", "AI"],
        popularity: 9.1,
        isPopular: false,
        isRecent: true,
        date: "2024-12-05",
        image: "/images/machine-learning.avif",
        comments: ["Python makes ML so much easier!", "Looking forward to more tutorials."],
    },
    {
        id: 6,
        title: "Getting Started with Next.js 14",
        content: "Next.js is the framework of choice for modern React developers...",
        categories: ["React", "Next.js", "Web Development"],
        tags: ["Next.js", "React", "Server-side Rendering"],
        popularity: 8.3,
        isPopular: true,
        isRecent: false,
        date: "2024-01-11",
        image: "/images/node-js.png",
        comments: ["I needed this guide!", "SSR is so useful."],
    },
    {
        id: 7,
        title: "Why Python is the Go-To Language for Data Science",
        content: "Python has become a dominant force in data science due to...",
        categories: ["Python", "Data Science", "Machine Learning"],
        tags: ["Python", "Data Analysis", "ML"],
        popularity: 8.8,
        isPopular: false,
        isRecent: true,
        date: "2024-06-30",
        image: "/images/python.avif",
        comments: ["Informative read.", "Python forever!"],
    },
    
];

export default blogs;